build:
  environment:
    php:
      version: 7.4
    docker: true

  tests:
    override:
      - command: 'docker-compose up -d'
      -
        command: 'vendor/bin/phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
filter:
  excluded_paths:
    - "test/"

checks:
  php:
    code_rating: true
    duplication: true

