name: CI

on:
  pull_request:

jobs:
  tests:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-versions: [ '7.4', '8.0' ]
        coverage-driver: [ 'pcov' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: "Start docker"
        run: "docker-compose up -d"

      - name: Install dependencies
        #if: steps.composer-cache.outputs.cache-hit != 'true'
        uses: php-actions/composer@v5
        with:
          args: --prefer-dist
          version: 2
          php_version: ${{ matrix.php-versions }}

      - name: "Run static analysis with phpstan/phpstan"
        run: "bin/phpstan analyse"

      - name: "Run static analysis with vimeo/psalm"
        run: "bin/psalm"

      - name: Test
        run: bin/phpunit -d memory_limit=-1 --coverage-clover clover.xml

      - name: Upload coverage to Codecov
        if: ${{ matrix.php-versions  == '7.4' }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}